[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1

[[plugins]]
repo = 'h1mesuke/vim-alignta'
on_cmd = ['Alignta', 'Align']

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = [
  'NERDTree', 'NERDTreeClose', 'NERDTreeFocus', 
  'NERDTreeMirror', 'NERDTreeCWD', 'NERDTreeFind', 
  'NERDTreeFromBookmark', 'NERDTreeToggle']
hook_add = '''
  nnoremap <silent> gr :NERDTreeToggle %:p:h<CR>
'''

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = ['TagbarToggle']
hook_add = '''
  nnoremap <silent> go :TagbarToggle<CR>
'''
