[[plugins]]
repo = 'scrooloose/syntastic'
on_i = 1
hook_srouce = '''
  set statusline+=%#warningmsg#
  set statusline+=%{SyntasticStatuslineFlag()}
  set statusline+=%*

  let g:syntastic_always_populate_loc_list = 1
  let g:syntastic_auto_loc_list = 1
  let g:syntastic_check_on_open = 1
  let g:syntastic_check_on_wq = 0
  let g:syntastic_error_symbol='E'
  let g:syntastic_warning_symbol='W'
'''

[[plugins]]
repo = 'klen/python-mode'
on_ft = 'python'


[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

